### PR TITLE
Make image in navbar clickable

### LINKED ISSUE #46: Clicking the icon should also lead to homepage
this is usually typical

### PR DESCRIPTION
**Pull request by Miepee**
Fixes #46 
I hope.

### CODE REVIEW

**Comment by duncathan** [comment]
did you test locally?

**Comment by Miepee** [comment]
no :D

**Comment by Miepee** [comment]
jekyll still had issues running locally and i havent (wanted to) put in the time to figure out why

**Review by duncathan — APPROVED** [review]
if this breaks something I reserve the right to make fun of you when I revert it

**Pull request merged**
